name: HIL

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  hil:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: thumbv7em-none-eabihf
    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev pkg-config
